### ISSUE TITLE
Show youtube thumbnail on latex export

### ISSUE THREAD

**Issue by SuperPat45** [sphinx-contrib/youtube#11]
Currently, the plugin only show a URL link to the YouTube video.

It will be awesome if the plugin could show:

The Thumbnails,   
The title  
the link URL

All centered and clickable.

**Comment by dham** [comment]
I'm happy to take a PR for that!

**Comment by SuperPat45** [comment]
I found youtube thumbnail images are available at:
https://i.ytimg.com/vi/%s/mqdefault.jpg

**Comment by dham** [comment]
I think #14 gives you enough customisability to have all of this if that's what you want.
