### ISSUE TITLE
No module named 'urlparse'

### ISSUE THREAD

**Issue by geoffreygarrett** [sphinx-contrib/youtube#13]
Fresh pip install in conda environment:

````
Exception occurred:
  File "/home/ggarrett/miniconda3/envs/tudat-blog/lib/python3.8/site-packages/sphinxcontrib/youtube/youtube.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
The full traceback has been saved in /tmp/sphinx-err-8jj48cne.log, if you want to report the issue to the developers.
````

Dependency missing?

**Comment by domdfcoding** [comment]
This is due to the version on PyPI being out of date, and the current maintainers don't have access to update it. There is an ongoing discussion about them gaining access.

In the interim you can install directly from GitHub:


```console
pip install git+https://github.com/sphinx-contrib/youtube
```

**Comment by geoffreygarrett** [comment]
Thanks for the quick solution. Shall I close this?
