### ISSUE TITLE
Please provide a LICENSE file

### ISSUE THREAD

**Issue by Un1Gfn** [sphinx-contrib/youtube#16]
According to setup.py, `license='BSD'`.

However a LICENSE file is [required](https://wiki.archlinux.org/title/PKGBUILD#license).

> ... BSD ... special cases ... technically each one is a custom license, because each one has its own copyright line ...

**Comment by dham** [comment]
Well a LICENSE (or LICENCE in UK English) file is not actually required, but I have no objection to one. Please file a PR.

**Comment by dham** [comment]
Fixed in #18
