### ISSUE TITLE
Support YouTube privacy-enhanced mode

### ISSUE THREAD

**Issue by akihironitta** [sphinx-contrib/youtube#22]
Hi, it'd be great to have support for privacy-enhanced mode for YouTube embedding. Implementation should be quite easy, i.e. replacing `youtube.com` with `youtube-nocookie.com`.

> To use Privacy Enhanced Mode:
> 1. Change the domain for the embed URL in your HTML from https://www.youtube.com to https://www.youtube-nocookie.com.

https://support.google.com/youtube/answer/171780

Let me know your thoughts!

**Comment by dham** [comment]
OK. In principle I'm fine with this. It's not obvious to me that this is what everyone wants, so I think it has to be switchable. The question then becomes what the best configuration option is. Should we do this via `conf.py` or do we add an option to the YouTube directive?

**Comment by rfc2822** [comment]
This feature would be really nice.

I suggest to add it as an option to the YouTube directive, because then it's per video (and in theory you may want to use the nocookie version for one video but not for another).

**Comment by 12rambau** [comment]
It can also be embed in the vimeo player: https://complianz.io/embedding-vimeo-videos-privacy-friendly/
