### ISSUE TITLE
use a thumbnail in the latex output

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/youtube#24]
In the current build of sphinxcontrib.youtube, the videos are displayed in the latex output as a link to the video. 

Checking on the web I realize that the thumbnail image can easily be acceced so instead of a link the latex output could be a figure with the youtube thumbnail, the title and the link as caption. 

I'm happy to make a PR if you guys think it could be useful. 

PS: I also check vimeo for the sake of it and it seems to work more or less the same way

**Comment by dham** [comment]
Thanks for looking into this. I don't think that we can make very many assumptions about how the author of a sphinx-latex document will intend their embedded videos to appear. For example, thumbnails are unlikely to be the right thing if the PDF is intended to be printed. That's the reason that we actually emit a `\sphinxcontribyoutube` or `\sphinxcontribvimeo` command and leave it to the author to redefine that command if they want something different from the default.

I therefore don't think that it makes sense to start adding built-in options for different output formatting. However, if you would like to put in a PR adding documentation (end of the README is fine) providing an example of how to redefine `\sphinxcontribyoutube` to produce the output you want, then that would be very much appreciated.

**Comment by 12rambau** [comment]
I'm not fluent in latex yet but I'll try to see how I can embed an image without downloading it to the `build` folder. If I manage to come up with something I'll let you know.

**Comment by 12rambau** [comment]
**EDIT**: it seems that's a duplicate from https://github.com/sphinx-contrib/youtube/issues/11. I'll see what I can do from a PR, there is effectively no way to do it only from the latex output (the images need to be downloaded). 

A solution could be: 
- always download the thumbnail to the latex output directory
- Use the current command as default (don't use the downloaded image) 
- Show in the documentation how to build a figure-like using the thumbnail 

Let me know what you think and I'll work on it

**Comment by dham** [comment]
Yes, I think that sounds like a good solution. I look forward to the PR and thanks for picking this up.
