### ISSUE TITLE
support align parameter as for the Image directive 

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/youtube#26]
Before discovering this extention, I was using an adaptation of the following [gist](https://gist.github.com/dbrgn/2922648). It was supporting the `align` parameter the same way as the image directive and moving to this lib is making all my youtube directive crash. 

Do you think you could add this parameter to the directive?

It seems that [@LSinterbotix](https://github.com/LSinterbotix) has already opened a [PR](https://github.com/sphinx-contrib/youtube/pull/23) in this sense, do you think it's sufficient or does it require extra work ?

**Comment by dham** [comment]
I've merged #23
