### ISSUE TITLE
Trying to use it.  But how to install it properly?

### ISSUE THREAD

**Issue by m-selig** [sphinx-contrib/youtube#31]
I am new to Sphinx.  I want to use this with my Sphinx document.  I've tried adding all these into my conf.py:

import os
import sys
#sys.path.insert(0, os.path.abspath('.'))
#sys.path.insert(0, os.path.abspath('./youtube-1.1.0'))
#sys.path.append(os.path.abspath('youtube-1.1.0'))
#sys.path.append(os.path.abspath('youtube'))
sys.path.append(os.path.abspath('sphinxcontrib'))
extensions = ['youtube']

But I am getting "ERROR: Unknown directive type "youtube" ".

Any help you can offer w/ how I should do the setup would be appreciated. Thanks.

**Comment by 12rambau** [comment]
you need to install it on your environment first. 

```
pip install sphinxcontrib-youtube
```

then simply add it to your configuration : 

```python
# in the conf.py file 

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # ...
    'sphinxcontrib.youtube',
    # ...
] 
```
