### ISSUE TITLE
Request: add configuration variable to block thumbnail downloading

### ISSUE THREAD

**Issue by garthz** [sphinx-contrib/youtube#42]
Would you consider making the new v1.2.0 thumbnail downloading optional?  It appears to be happening even when the build target is HTML, even though there do not appear to be any thumbnail references in the generated HTML.

I use your plug-in to generate course sites with hundreds of YouTube and Vimeo links in my reference material, so the downloading represents a huge overhead on any clean build.  Branch 1.1.0 builds super-fast without this feature.

**Comment by dham** [comment]
Well I can certainly merge a PR to that effect. Ideally it would be a pretty transparent process, but I haven't thought through the mechanics of how it would have to work.
