### ISSUE TITLE
Videos should not be embeded in EPUB files

### ISSUE THREAD

**Issue by adityatoshniwal** [sphinx-contrib/youtube#46]
Hi,

Thank you for the extension.
I am from pgAdmin4 team and we're creating docs with output as - HTML, EPUB and PDF. With this extension, HTML uses embedded and PDF shows links as expected. But, EPUB shows embedded which I think is not correct as EPUB is used for offline viewing. It should show a link just like PDF.
If I may raise a PR, are you willing to accept it to fix this?

Thanks.

**Comment by dham** [comment]
Yes please! Also, good timing. I was planning a release over Christmas so if you get the PR in in the next week or so then we should be able to get it up on PyPI quickly.

**Comment by adityatoshniwal** [comment]
@dham Thank you. Will raise a PR ASAP.

**Comment by adityatoshniwal** [comment]
@dham PR raised. Please review.

**Comment by dham** [comment]
PR Merged. Thanks for the contribution!
