### ISSUE TITLE
document installation 

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/youtube#48]
THe documentation doesn't explain how to install the lib which is not straight forward (sphinxcontrib.youtube)

**Comment by dham** [comment]
I agree this should be in the docs, but it is pretty straightforward:
`pip install sphinxcontrib-youtube`.

It is documented here:
https://pypi.org/project/sphinxcontrib-youtube/

**Comment by RNF-SI** [comment]
And how to add it to our project? 
I tried to put `sphinx.ext.youtube` on extensions in the `conf.py` file but it is not working... 
Thank's !

**Comment by 12rambau** [comment]
it's effectively also missing: in your conf.py, add the following: 

```python

extentions = [
    # you other extentions
    "sphinxcontrib.youtube"
]
```

`sphinx.ext` is only for built-in extention of sphinx (like `napoleon` or `autodoc`)
