### ISSUE TITLE
pdf : thumbnail print at the wrong place

### ISSUE THREAD

**Issue by yboujraf** [sphinx-contrib/youtube#50]
Dear all,

I have cloned your repository.
I tried to generate the hml and pdf documents.

For the html documentation, everything is ok as per the .rst file.

- html

![image](https://user-images.githubusercontent.com/6151258/223844535-d92e8522-2f41-45ec-aaea-f0c72413a335.png)

For the pdf file, the thumbnail is added at the next page

- pdf

![image](https://user-images.githubusercontent.com/6151258/223844431-732e982b-b439-4e28-a957-a9762dcb5ea8.png)

**Comment by 12rambau** [comment]
I think that's just a sizing issue. as you have it at hand, what happens when you change width ?

**Comment by yboujraf** [comment]
Dear @12rambau 

No influence. Stills the same.

..  youtube:: dQw4w9WgXcQ
   :width: 25%

**Comment by dham** [comment]
Changing the width like that won't affect the PDF output. As the documentation says, we simply output a call to `\sphinxcontribyoutube` and it's for you to customise the definition of that LaTeX macro to achieve whatever it is you want.
