### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by t-b** [sphinx-contrib/youtube#52]
It would be nice to have a new release as I just hit https://github.com/sphinx-contrib/youtube/pull/40 as well.

**Comment by rlaphoenix** [comment]
A new release was made [v1.3.0](https://github.com/sphinx-contrib/youtube/releases/tag/v1.3.0) but a release was not put onto PyPI. I'm kindly requesting a wheel or srcdist package is pushed to PyPI for v1.3.0.

**Comment by dham** [comment]
Releases 1.3 and 1.4 are now on PyPI
