### ISSUE TITLE
:privacy_mode: has no effect

### ISSUE THREAD

**Issue by phw** [sphinx-contrib/youtube#57]
Using sphinxcontrib-youtube==1.2.0 and code like this:

```rst
.. youtube:: zMAc-UyO0NA
   :privacy_mode:
```

But the `:privacy_mode:`  parameter does not seem to work, the generated URL is not using the privacy URL. The generated HTML is

```html
<iframe allowfullscreen="true" src="https://www.youtube.com/embed/zMAc-UyO0NA" style="border: 0; height: 345px; width: 560px">
</iframe>
```

**Comment by 12rambau** [comment]
can you check with v1.3.0 ? to confirm that the error still exists

**Comment by phw** [comment]
@12rambau Thanks for the feedback. I hadn't realized there was a 1.3 release as it wasn't on pypi yet. Anyway, I have now installed the latest version directly from git. The issue is still the same, the iframe embeds from "https://www.youtube.com/".
