### ISSUE TITLE
Pypi release of 1.3.0

### ISSUE THREAD

**Issue by kwavnet** [sphinx-contrib/youtube#60]
currently very old 1.2.0 can be found on pypi as the latest.
Please release the latest to pypi.

And thanks by the way for the very helpful project

**Comment by kwavnet** [comment]
Relates to https://github.com/sphinx-contrib/youtube/issues/52#issuecomment-1537368436 - in case that hasn't got the level of attention, the comment should have gotten

**Comment by dham** [comment]
Releases 1.3 and 1.4 are now on PyPI
