### ISSUE TITLE
Video thumbnail missing in PDF

### ISSUE THREAD

**Issue by lorforlinux** [sphinx-contrib/youtube#67]
Hey, is there any way to display thumbnails in the PDF output of a sphinx project?

![image](https://github.com/sphinx-contrib/youtube/assets/20015794/da8affa8-0fbe-42eb-b5cd-ae0396dd6471)

We were using this format of adding YouTube videos: https://docs.beagleboard.org/latest/intro/contribution/rst-cheat-sheet.html#youtube-videos

But now we want to switch from that bulky format to the sleek format `sphinxcontrib-youtube` provides. I am willing to work on this improvement but bit new to all this, if possible please share some material to help with the development.

**Comment by lorforlinux** [comment]
I am not sure but this PR seems related to the issue we are facing. 
https://github.com/sphinx-contrib/youtube/pull/43

**Comment by dham** [comment]
The PDF output comes via the LaTeX backend. This plugin emits a latex command for each video, and the default implementation of that command just drops in the link that you show. It's up to the user to provide a different implementation to render the videos how they want to. The documentation contains an example of inserting a thumbnail that you could customise for your own use: https://sphinxcontrib-youtube.readthedocs.io/en/latest/usage.html#latex

**Comment by lorforlinux** [comment]
@dham Thanks a lot for the reference, I managed to fix the issue.

Here is the commit link if anybody else faces the same problem, 
https://openbeagle.org/lorforlinux/docs.beagleboard.io/-/commit/6949b085ea3263648fb6e8852c8362bb2065038b
