### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by MagicRedDeer** [sphinx-contrib/youtube#9]
Please publish the latest version to pypi and extending support for newer python versions

**Comment by rahulbhadani** [comment]
@MagicRedDeer Check this: https://pypi.org/project/ytsphinx/

**Comment by dham** [comment]
Unfortunately I don't control sphinxcontrib.youtube on pipit so I can't push there.

**Comment by jedbrown** [comment]
If @shomah4a is not willing to offer https://pypi.org/project/sphinxcontrib.youtube/ (unmaintained since 2015), this project could at least update `setup.py` to not reference it.

@rahulbhadani Do you recommend moving to ytsphinx from https://github.com/Peque/sphinxembeddedvideos ? Will you make normal releases? It'd be great if the community could agree on one maintained fork.

**Comment by rahulbhadani** [comment]
@jedbrown I will look at what's difference between ytsphinx that I have forked and sphinx nxembeddedvideos that you referred to. I will integrate changes to ytsphinx.

**Comment by s-m-e** [comment]
Hi guys. Sorry, but this looks a little messed up, do not you think? I am **looking for a reliable, longer-term way to make a package depend on this** ... Took me a while to fully understand this discussion. There are:

- `sphinx-contrib/youtube`, available only from Github (?) via `pip install git+https://github.com/sphinx-contrib/youtube.git@master`. Maintained *here* by @dham (?).
- Special case: `pip install sphinxcontrib.youtube` gives you an outdated (2015) version of the above. Package under the control of @shomah4a (?). It points to [another Github repository](https://github.com/shomah4a/sphinxcontrib.youtube), which is strictly speaking not a fork of *this* repo.
- `ytsphinx`, a fork, available via `pip install ytsphinx`. Maintained [here](https://github.com/rahulbhadani/ytsphinx) by @rahulbhadani. Ahead of [sphinx-contrib/youtube](https://github.com/sphinx-contrib/youtube) by a few commits.
- `sphinxembeddedvideos`, another fork, available via `pip install sphinxembeddedvideos`. Maintained [here](https://github.com/Peque/sphinxembeddedvideos) by @Peque. Both ahead and behind [sphinx-contrib/youtube](https://github.com/sphinx-contrib/youtube) by a few commits with added support for peertube.social (?).

Besides, `setup.py` in *this repository* links to a [deleted repository on bitbucket](http://bitbucket.org/birkenfeld/sphinx-contrib) which used to belong to @birkenfeld.

What would you recommend? Would you consider consolidating your efforts into a single repository and PyPI package?

**Comment by Peque** [comment]
@s-m-e :joy: 

I created the fork exactly to be able to upload it to PyPI and, as you mention, to add support for Peertube or other video platforms. At that moment, this repo seemed to be unmaintained.

I am willing to accept PRs to keep my fork up-to-date, and the corresponding PyPI package as well. I'd be happy to have my changes integrated into this repository and remove my fork all together if the maintainer of this repository agrees to integrate them and pushes a package to PyPI. :blush:

**Comment by dham** [comment]
Sorry for not getting back to this. You are correct that I don't put much work into this. I took it over as a dead project in order to get my PRs merged so that our documentation would keep building. I am more than happy to have other people get involved if they want to be more active than me.

**Comment by jzohrab** [comment]
Hi @dham, I have some cycles and would like to see this become more stable/usable.  On first glance, it appears that this repo should be the standard, just because it's in the `sphinx-contrib` org. :-)

"I am more than happy to have other people get involved if they want to be more active than me." - sure, I can give this a shot, if you let me know briefly what's needed to get this going.  Though I've written some projects in Python I'm not experienced in this language, and am not sure what is involved to get this to a good state.  For PyPi, it appears I need to do (this)[https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56] ... I could create a branch in a fork for packaging it.

**Comment by jzohrab** [comment]
@rahulbhadani - I'm getting an error with `ytsphinx`, fyi: "extension 'ytsphinx' has no setup() function; is it really a Sphinx extension module?"  The repo https://github.com/rahulbhadani/ytsphinx doesn't have issues enabled so I can't report it there.  If you enable issues we could continue this over there.  Cheers, jz

EDIT UPDATE: ah my conf was wrong, should have had `extensions = [ ... 'ytsphinx.youtube' ]` ... a README note would have helped :-)  Cheers!  I'll update _this_ repo's readme when/if I can.

**Comment by dham** [comment]
OK, so I don't actually control who has write access to this repo. However if you create a branch in a fork then I can merge it.

**Comment by dham** [comment]
Additionally @shoma4a seems not to have an accessible email address, or to be active on any of their public repositories, so I am not quite sure how to reach them.

**Comment by dham** [comment]
OK. I am a muppet. @shoma4a is also his twitter handle. I should have thought of that. I have sent him a DM and we'll see where that takes us.

**Comment by dham** [comment]
OK. For info, and as noted immediately above, I have raised an issue on PyPI to request transfer of the name `sphinxcontrib.youtube` on PyPI.

**Comment by dham** [comment]
For info, I have come back from my holidays to discover that the PyPi package was transferred to me at the end of July. I will try to make an updated release next week.

**Comment by dham** [comment]
Happy days. There is now a shiny new prerelease version up on PyPI:
```
pip install sphinxcontrib-youtube==1.0.0.dev20210831
```
Unless someone points out a massive error in the next few days, I will make a stable release.

I am aware of the two PRs currently active, I will release those as soon as they merge.

**Comment by jonas-eschle** [comment]
Hey, it looks all good to me! What about a stable release? (Or if not stable, I guess the normal way is to go for a 0.x version instead of the pre-release)

**Comment by dham** [comment]
> Hey, it looks all good to me! What about a stable release? (Or if not stable, I guess the normal way is to go for a 0.x version instead of the pre-release)

I made a 1.0.0 release on 5 September. It's [on PyPI](https://pypi.org/project/sphinxcontrib-youtube/) and tagged in this repo.
